server:
  port: 7072
  
#eureka:
#    instance:
 #     hostname: localhost
spring:
  application:
    name: book-ticket
  datasource:
    password: mani
    url: jdbc:mysql://localhost:3306/pip
    username: root
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true